### ISSUE TITLE
Won't install on sky factory 3!

### ISSUE THREAD

**Issue by 21harrisont** [BlakeBr0/MysticalAgradditions#1]
I tried every single mystical agriculture version and every agradditions version! This dosen't work! It either says I have to update mystical agriculture or give me an error!

**Comment by 21harrisont** [comment]
WORST MOD EVER!!!

**Comment by BlakeBr0** [comment]
Try using Mystical Agriculture 1.5.2 and Mystical Agradditions 1.0.2.
