### ISSUE TITLE
Having troubles auto crafting with the essesnces

### ISSUE THREAD

**Issue by purestone9** [BlakeBr0/MysticalAgradditions#10]
I'm trying to auto craft grass, and it is not working. I'm using the assembler from Immersive Engineering. The assembler is working, but when I tell it to craft anything that is using the essences from Mystical Agriculture it is not working.

**Comment by purestone9** [comment]
Would it be possible to ore dictionary the different essences into different essences other that essenceTire1, essenceTire2 ect

**Comment by BlakeBr0** [comment]
If the auto crafter doesnt work without oredictionary, thats not an issue on my part. The point of the oredictionary entries is for things that want to use all of the essences in a tier.
