### ISSUE TITLE
Awakened Supremium Paxel recipe

### ISSUE THREAD

**Issue by Hokmun** [BlakeBr0/MysticalAgradditions#100]
**Describe the bug**
Missing recipe for Awakened Supremium Paxel

**To Reproduce**
Try to craft Awakened Supremium Paxel

**Screenshots / Scripts / Logs**
N/A

**Versions (please complete the following information):**
 - Minecraft: 1.20.1
 - Forge: 47.1.3
 - Cucumber: 7.0.0
 - Mystical Agriculture: 7.0.1
 - Mystical Agradditions: 7.0.0

**Comment by BlakeBr0** [comment]
Fixed in version 7.0.1.
