### ISSUE TITLE
Insanium farmland with Inferium seeds planted doesn't yield 350% essence

### ISSUE THREAD

**Issue by TiphaineLAURENT** [BlakeBr0/MysticalAgradditions#101]
**Describe the bug**
Insanium farmland with Inferium seeds planted doesn't yield 350% essences

**To Reproduce**
- Plant an Inferium seeds on an insanium farmland
- Wait for it to grow
- Harvest it for 1 essence

**Expected behavior**
It should produce 350% of the original output

**Versions (please complete the following information):**
 - Minecraft: 1.20.1
 - Forge: 47.1.3
 - Cucumber: 7.0.0
 - Mystical Agriculture: 7.0.1
 - Mystical Agradditions: 7.0.0

**Comment by BlakeBr0** [comment]
Fixed in version 7.0.2 of Mystical Agriculture.
