### ISSUE TITLE
[1.16.5] Low paxel damage

### ISSUE THREAD

**Issue by Ripper1233** [BlakeBr0/MysticalAgradditions#104]
**Describe the bug**
All paxels have same damage of 5. Striking mobs confirm that.

**To Reproduce**
Get a paxel, check damage.

**Expected behavior**
All paxels have different and much higher damage.

**Screenshots / Scripts / Logs**
![image](https://github.com/BlakeBr0/MysticalAgradditions/assets/32108737/8f968c89-d8ce-4945-8c8e-6a7f6f5fffe6)
![image](https://github.com/BlakeBr0/MysticalAgradditions/assets/32108737/9b96e5cf-0472-4a78-9da9-29ea4c2741aa)
etc.

**Versions:**
 - Minecraft: 1.16.5
 - Forge: 36.2.34
 - Cucumber: 4.1.12
 - Mystical Agriculture: 4.2.6
 - Mystical Agradditions: 4.2.4
 - Singleplayer or Multiplayer: checked in single

**Comment by BlakeBr0** [comment]
Unfortunately the 1.16 version of Mystical Agradditions is out of support. I just confirmed and this is fixed in the latest release for 1.20. I'm not 100% sure but there may be mods that can be used to change attack damage.
