### ISSUE TITLE
Please update your Tinkers Construct support (1.19.2)

### ISSUE THREAD

**Issue by Gitcrafter** [BlakeBr0/MysticalAgradditions#106]
Please update your tinkers support, the custom traits of your materials don´t work with the new rewrite for 1.19.2, they show as invalid modifiers

![2024-04-28_16 32 09](https://github.com/BlakeBr0/MysticalAgradditions/assets/81863925/4f2e64d4-4e27-41de-b7ea-6d434094bfda)

**Comment by BlakeBr0** [comment]
Fixed in 6.0.4

**Comment by Gitcrafter** [comment]
Thank you.
