### ISSUE TITLE
Tinker's Update has stats being all 1s

### ISSUE THREAD

**Issue by DMSledge** [BlakeBr0/MysticalAgradditions#107]
**Describe the bug**
With the newest version of Tinkers they have changed something and it is causing all agradittions materials to have mining speed and damage of 1.

**To Reproduce**
Updated Tinkers Construct to the newest version.

**Expected behavior**
Each metal should have different stats.

**Versions (please complete the following information):**
 - Minecraft: 1.19.2
 - Forge: 43.3.0
 - Cucumber:
 - Mystical Agriculture: 6.0.14
 - Mystical Agradditions: 6.0.4
 - Singleplayer or Multiplayer:

**Comment by BlakeBr0** [comment]
Fixed in version 6.0.5.
