### ISSUE TITLE
im trying to make awakened supremium armor on 1.20.1 with mystical agridditions and i put the essence in the essence vessels and it says its missing no matter what i do im on forge in single player as well

### ISSUE THREAD

**Issue by Ceasingbeet2982** [BlakeBr0/MysticalAgradditions#108]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots / Scripts / Logs**
Please add your logs and scripts (if applicable).

**Versions (please complete the following information):**
 - Minecraft:
 - Forge:
 - Cucumber:
 - Mystical Agriculture:
 - Mystical Agradditions:
 - Singleplayer or Multiplayer:

**Comment by BlakeBr0** [comment]
Without any information it's hard to tell what's wrong. Have you figured out the issue on your end?

**Comment by BlakeBr0** [comment]
I'm going to close this due to inactivity. If this is still an issue on the latest version you can reply here.
