### ISSUE TITLE
mysticalagradditions[1.11.2]-1.1.1 crashes with java.lang.NoSuchFieldError: itemBaseEssenceNugget

### ISSUE THREAD

**Issue by sandalle** [BlakeBr0/MysticalAgradditions#11]
Updated to mysticalagradditions[1.11.2]-1.1.1 and mysticalagriculture[1.11.2]-1.5.8 and now now get this crash on client or server load: [crash-2017-07-22_20.36.58-client.txt](https://github.com/BlakeBr0/MysticalAgradditions/files/1167839/crash-2017-07-22_20.36.58-client.txt)

Reverting back to mysticalagradditions[1.11.2]-1.1.0 allows both server and client to load

**Comment by BlakeBr0** [comment]
1.1.2 which I just submitted should fix it

**Comment by sandalle** [comment]
mysticalagradditions[1.11.2]-1.1.2 loaded on both client and server for me, thank you for the quick fix! :)
