### ISSUE TITLE
[Suggestion] add Malum support! 

### ISSUE THREAD

**Issue by FullMetalMaster** [BlakeBr0/MysticalAgradditions#117]
1.20.1 

cthonic gold, soulstone, natural quartz are some thing you can get in the mod but theres also magic metals that I think would be nice if you could grow them as well! 

https://www.curseforge.com/minecraft/mc-mods/malum

**Comment by BlakeBr0** [comment]
Thanks for the suggestion! I don't have any plans to add additional mod support to the base mod, but it's always possible to add custom crops using Mystical Customization or by creating an addon mod/integration.
