### ISSUE TITLE
Item's without colours

### ISSUE THREAD

**Issue by Hurifire** [BlakeBr0/MysticalAgradditions#13]
Tinker's support for this mod isn't proper, all items are white.
Example:
https://gyazo.com/4c997c366ff2dd98636e96a37424ba50

**Comment by BlakeBr0** [comment]
versions?

**Comment by Hurifire** [comment]
Forge Mod Loader version 14.22.0.2467
mysticalagriculture[1.12]-1.6.3
mysticalagradditions[1.12]-1.2.3
TConstruct-1.12-2.7.2.19
