### ISSUE TITLE
Tinkers Construct Tools

### ISSUE THREAD

**Issue by BJR1984** [BlakeBr0/MysticalAgradditions#16]
Soulium TC tools are only dropping tier 1 mob chunk

not dropping any Experience, Zombie, Pig, Chicken, Cow, Sheep, Slime, Skeleton, Creeper, Spider, Rabbit, Guardian, Blaze, Ghast, Enderman, Wither Skeleton, Blizz, Blitz, Basalz Chunks

**Comment by BlakeBr0** [comment]
1.12 right?

**Comment by BJR1984** [comment]
yes
