### ISSUE TITLE
IE External Heater Integration

### ISSUE THREAD

**Issue by FiveEYZ** [BlakeBr0/MysticalAgradditions#19]
hey thanks for this mod and the TC Integration!

Could you also please add immersive engineering Integration?
In this case it would be the External Heater from IE is not currently able to heat the furnaces.

https://github.com/BluSunrize/ImmersiveEngineering/blob/fc022675bb550318cbadc879b3f28dde511e29c3/src/main/java/blusunrize/immersiveengineering/api/tool/ExternalHeaterHandler.java#L26

**Comment by BlakeBr0** [comment]
I will be closing this issue as the 1.12 version is EOL.
