### ISSUE TITLE
Question: Cruxes, what are they for?

### ISSUE THREAD

**Issue by kingchills** [BlakeBr0/MysticalAgradditions#2]
Hey, I'm excited about the things you've added so far, I was curious what the Cruxes do, i've made a nether star crux, but i'm not sure what I'm supposed to do with it.  Has any functionality for it been implemented yet or is it something that's in the works?

**Comment by BlakeBr0** [comment]
goes under a nether star crop

**Comment by kingchills** [comment]
Ahhs, thanks for the heads up!
