### ISSUE TITLE
[Feature Request] AOE Mining on Paxels

### ISSUE THREAD

**Issue by Boolyman** [BlakeBr0/MysticalAgradditions#21]
I am really trying to find a mod that offers a decent alternative to Actually Addition's Mining Drills... and the closest thing would be a Paxel with 3x3 (and preferrably an option for 5x5) mining capabilities.  The other tools in Mystical Agriculture have this option via a tool core, but the paxel from the Aggriditions mod does not seem to.  Or, if it does, it's not listed in JEI.

**Comment by BlakeBr0** [comment]
I do plan on adding a mining aoe charm, probably not 5x5 though
