### ISSUE TITLE
Tier 6 inferium seed drops one inferium essence when harvested by machine

### ISSUE THREAD

**Issue by ouroborus** [BlakeBr0/MysticalAgradditions#22]
Tier 6 inferium seed drops one inferium essence when harvested by machine (both gentle and breaking). Mystical agriculture's tier 1-5 inferium seeds drop 1-5 inferium essence as appropriate when harvested by machine. (User harvesting produces 6 essence as expected.)

Minecraft 1.12.2
ATM3 4.4
Mystical Agriculture 1.6.5
Mystical Agradditions 1.2.5

**Comment by BlakeBr0** [comment]
Is it the actually additions machine?

**Comment by ouroborus** [comment]
Cyclic's harvester and one from another mod that I can't remember off the top of my head.

**Comment by BlakeBr0** [comment]
Interesting, might be because I forgot to update the crops with the new getDrops method. I'll have to test it out later

**Comment by jarquafelmu** [comment]
I have the same issue with the actually additions farmer

**Comment by BlakeBr0** [comment]
Just tested and the change I made seems to fix it \o/
Hopefully I can get a new release out soonish
