### ISSUE TITLE
How do you get dragon scales?

### ISSUE THREAD

**Issue by uehlbran** [BlakeBr0/MysticalAgradditions#25]
I killed the ender dragon, got the egg but can't do anything to get dragon scales. What do I need to do here?

Also can you get dragons breath from seeds or another method?

**Comment by BlakeBr0** [comment]
They should be dropping from the dragon when it dies.

**Comment by jonnytest1** [comment]
dragon breath was from clicking the purple magic attack with a bottle but i cdont know for the scales either oO (there are scales from a different mod that drop though)
