### ISSUE TITLE
Tier 6 Inferium Seeds - IE Garden cloche compatibility

### ISSUE THREAD

**Issue by Skar78** [BlakeBr0/MysticalAgradditions#26]
Playing on ATM3. 

Inferium Seeds Tier 1-5 work in an IE Garden Cloche - Tier 6 does not.

Little bit unsure if it would have special soil requirements - but it works on normal soil outside the Cloche.

**Comment by BlakeBr0** [comment]
https://minecraft.curseforge.com/projects/mystagrad-cloche-compat?gameCategorySlug=mc-mods&projectID=288959 

Looks like someone made an addon that adds this.
