### ISSUE TITLE
[Suggestion] Insanium

### ISSUE THREAD

**Issue by 47delasPECII** [BlakeBr0/MysticalAgradditions#31]
Insanium tools plus insanium tool parts for tinkers? cuz at the moment there is no use for insanium! (no need for insanium armor the supremium armor is really good)

**Comment by SinbadEV** [comment]
Yes! And:

I think the Cruxs should use Insanium Ingots (or nuggets... or blocks) in their recipe.

Traits for using Insanium as a tool material could be something suitably weird like "Hallucinogenic" (maybe causing random mob sounds to play and applying nausea while the tool is in hand) and "Berserker" (maybe each use damages the player and uses hunger).

**Comment by BlakeBr0** [comment]
I know this is an old suggestion but I'll just mention that I have no plans to ever add Insanium tier gear as it's doesn't make sense with Supremium tools being unbreakable. Insanium was always just meant for crops only, and I added the extra crafting items for mod pack devs to use.
