### ISSUE TITLE
Nether Star Seed Duplication

### ISSUE THREAD

**Issue by kingchills** [BlakeBr0/MysticalAgradditions#4]
Mystical Agriculture Version: 1.5.2b
Mystical Agraddaition Version: 1.0.2a

Issue: When planting a nether start crop seed on farmland, and breaking immediately (not allowing the crop to progress) there is a significant chance you will get two seeds back instead of one.  This does not seem to happen when planting on soil that is above the Nether Star Crux.

Expected:  Only receive back the seed that was originally planted without crop growth.

**Comment by BlakeBr0** [comment]
Can't reproduce.

**Comment by kingchills** [comment]
Note in this video I start with 3 seeds on my hot bar, by the end of the video I have 22.

https://youtu.be/1JjqYEhcMLY

**Comment by BlakeBr0** [comment]
Is there something else effecting the crops, because I can't reproduce what you're saying.

**Comment by kingchills** [comment]
Ah Ha! Found it, sorry there was something effecting it that I didn't realize.   Sorry for the trouble.

**Comment by BlakeBr0** [comment]
What was it?
