### ISSUE TITLE
insanium (tier 6)inferium seeds 

### ISSUE THREAD

**Issue by ahm57193** [BlakeBr0/MysticalAgradditions#40]
tier 6 inferium seeds are grown instantly but dont drop the inferium till i break it dont work with right click

but i didnt try the machines to harvest yet
i tried alot but the crop itself cant be harvested till its broken
actually additions farmer work well so no problem

**Comment by Fireztonez** [comment]
You can configure the Right-click to harvest if you add and configure a mod called SimpleHarvest (https://minecraft.curseforge.com/projects/simpleharvest?gameCategorySlug=mc-mods&projectID=240783)

The right-click to harvest is not added by mystical agriculture or mystical agraddition, so this is not really a bug from this mod...

I have configured all plants of mystical and xl food in my modpack with SimpleHarvest and everything works perfectly!

**Comment by BlakeBr0** [comment]
I'm going to close this as this is for a version which is no longer supported.
