### ISSUE TITLE
[Suggestion] Slag and Rich slag seeds

### ISSUE THREAD

**Issue by niklas2233** [BlakeBr0/MysticalAgradditions#44]
Hey could you add rich slag and slag seeds. that would be awesome since there is no real way to make it unless you go by chance. or make it possible to add you own seeds or an easier way or just a tutorial on it

also it would be nice if you could add cinnabar seeds

**Comment by BlakeBr0** [comment]
I think these are out of scope. I generally try to stick to 'primary output' materials for crops. In more modern versions Mystical Customization can be used to add custom crops.
