### ISSUE TITLE
Prosperous trait stops working

### ISSUE THREAD

**Issue by ThomasKidder** [BlakeBr0/MysticalAgradditions#49]
I've put a prosperous tool in a controlled miner with a block placer (which mines about 7 blocks/second). It produced one prosperity shard pretty quickly but then leaving it for an hour or so (must have mined like 20k+ blocks at least), it did not produce any more. I also tried mining manually ~2000 blocks to try and determine it if was an issue with the controlled miner, but still didn't get any shards. Also tried restarting the server. The pickaxe is only mining cobblestone but looking at the code it doesn't seem like that should matter (looks like just a 1/300 random chance on block break). I previously had something similar happen with another prosperous pickaxe.. seems like it works at first but then stops? 

Let me know if this is a known issue or there is some workaround for this :\

Mod version: 1.3.2
Minecraft version: 1.12.2

**Comment by ThomasKidder** [comment]
Seems like if I restart the server it again works exactly once and then stops? Or maybe it is waiting a while? Not sure.

**Comment by ThomasKidder** [comment]
Also noting that the behavior is actually predictable, the tool produces exactly one shard and then stops producing them. Each server restart resets the state and allows the tool to produce another shard, and then it stops after, so it seems like somehow the server state is getting messed up after it produces a shard. 

Seems like someone else has this issue, so I'm pretty confident its not some weird glitch in the server (which is Dungeons Dragons & Space Shuttles):
https://www.curseforge.com/minecraft/mc-mods/mystical-agradditions?comment=126

**Comment by BlakeBr0** [comment]
I'm going to be closing this issue as the 1.12 version is EOL.
