### ISSUE TITLE
[1.15.2] add zh_tw.json file

### ISSUE THREAD

**Issue by fantasyair18** [BlakeBr0/MysticalAgradditions#50]
{
  "itemGroup.mysticalagradditions": "Mystical Agradditions",

  "block.mysticalagradditions.insanium_block": "§5究極精華塊",
  "block.mysticalagradditions.insanium_ingot_block": "§5究極精華磚",
  "block.mysticalagradditions.insanium_gemstone_block": "§5究極精華寶石磚",
  "block.mysticalagradditions.insanium_farmland": "§5究極精華耕地",
  "block.mysticalagradditions.inferium_coal_block": "§e下級精華煤炭磚",
  "block.mysticalagradditions.prudentium_coal_block": "§a初級精華煤炭磚",
  "block.mysticalagradditions.tertium_coal_block": "§6中級精華煤炭磚",
  "block.mysticalagradditions.imperium_coal_block": "§b高級精華煤炭塊磚",
  "block.mysticalagradditions.supremium_coal_block": "§c終極精華煤炭磚",
  "block.mysticalagradditions.insanium_coal_block": "§5究極精華煤炭磚",
  "block.mysticalagradditions.nether_star_crux": "地獄之星核心",
  "block.mysticalagradditions.dragon_egg_crux": "龍蛋核心",

  "item.mysticalagradditions.insanium_essence": "§5究極精華",
  "item.mysticalagradditions.insanium_ingot": "§5究極精華錠",
  "item.mysticalagradditions.insanium_nugget": "§5究極精華粒",
  "item.mysticalagradditions.insanium_gemstone": "§5究極精華寶石",
  "item.mysticalagradditions.nether_star_shard": "地域之星碎片",
  "item.mysticalagradditions.withering_soul": "凋靈靈魂碎片",
  "item.mysticalagradditions.dragon_egg_chunk": "龍蛋碎片",
  "item.mysticalagradditions.dragon_scale": "終界龍靈魂碎片",
  "item.mysticalagradditions.creative_essence": "創造精華",
  "item.mysticalagradditions.inferium_coal": "§e下級精華煤炭",
  "item.mysticalagradditions.prudentium_coal": "§a初級精華煤炭",
  "item.mysticalagradditions.tertium_coal": "§6中級精華煤炭",
  "item.mysticalagradditions.imperium_coal": "§b高級精華煤炭",
  "item.mysticalagradditions.supremium_coal": "§c終極精華煤炭",
  "item.mysticalagradditions.insanium_coal": "§5究極精華煤炭",

  "item.mysticalagradditions.inferium_paxel": "§e下級精華全能工具",
  "item.mysticalagradditions.prudentium_paxel": "§a初級精華全能工具",
  "item.mysticalagradditions.tertium_paxel": "§6中級精華全能工具",
  "item.mysticalagradditions.imperium_paxel": "§b高級精華全能工具",
  "item.mysticalagradditions.supremium_paxel": "§c終極精華全能工具",

  "tooltip.mysticalagradditions.drop_chance": "%s 掉落機率",

  "jei.desc.mysticalagradditions.withering_soul": "由凋零掉落。",
  "jei.desc.mysticalagradditions.dragon_scale": "由終界龍掉落。",

  "cropTier.mysticalagradditions.6": "6",

  "crop.mysticalagradditions.nether_star": "Nether Star",
  "crop.mysticalagradditions.dragon_egg": "Dragon Egg"
}

**Comment by fantasyair18** [comment]
> {
> "itemGroup.mysticalagradditions": "Mystical Agradditions",
> 
> "block.mysticalagradditions.insanium_block": "§5究極精華塊",
> "block.mysticalagradditions.insanium_ingot_block": "§5究極精華磚",
> "block.mysticalagradditions.insanium_gemstone_block": "§5究極精華寶石磚",
> "block.mysticalagradditions.insanium_farmland": "§5究極精華耕地",
> "block.mysticalagradditions.inferium_coal_block": "§e下級精華煤炭磚",
> "block.mysticalagradditions.prudentium_coal_block": "§a初級精華煤炭磚",
> "block.mysticalagradditions.tertium_coal_block": "§6中級精華煤炭磚",
> "block.mysticalagradditions.imperium_coal_block": "§b高級精華煤炭塊磚",
> "block.mysticalagradditions.supremium_coal_block": "§c終極精華煤炭磚",
> "block.mysticalagradditions.insanium_coal_block": "§5究極精煤炭磚",
> "block.mysticalagradditions.nether_star_crux": "地獄之星核心",
> "block.mysticalagradditions.dragon_egg_crux": "龍蛋核心",
> 
> "item.mysticalagradditions.insanium_essence": "§5究極精華",
> "item.mysticalagradditions.insanium_ingot": "§5究極精華錠",
> "item.mysticalagradditions.insanium_nugget": "§5究極精華粒",
> "item.mysticalagradditions.insanium_gemstone": "§5究極精華寶石",
> "item.mysticalagradditions.nether_star_shard": "地域之星碎片",
> "item.mysticalagradditions.withering_soul": "凋靈靈魂碎片",
> "item.mysticalagradditions.dragon_egg_chunk": "龍蛋碎片",
> "item.mysticalagradditions.dragon_scale": "終界龍靈魂碎片",
> "item.mysticalagradditions.creative_essence": "創造精華",
> "item.mysticalagradditions.inferium_coal": "§e下級精華煤炭",
> "item.mysticalagradditions.prudentium_coal": "§a初級精華煤炭",
> "item.mysticalagradditions.tertium_coal": "§6中級精華煤炭",
> "item.mysticalagradditions.imperium_coal": "§b高級精華煤炭",
> "item.mysticalagradditions.supremium_coal": "§c終極精華煤炭",
> "item.mysticalagradditions.insanium_coal": "§5究極精華煤炭",
> 
> "item.mysticalagradditions.inferium_paxel": "§e下級精華全能工具",
> "item.mysticalagradditions.prudentium_paxel": "§a初級精華全能工具",
> "item.mysticalagradditions.tertium_paxel": "§6中級精華全能工具",
> "item.mysticalagradditions.imperium_paxel": "§b高級精華全能工具",
> "item.mysticalagradditions.supremium_paxel": "§c終極精華全能工具",
> 
> "tooltip.mysticalagradditions.drop_chance": "%s 掉落機率",
> 
> "jei.desc.mysticalagradditions.withering_soul": "由凋零掉落。",
> "jei.desc.mysticalagradditions.dragon_scale": "由終界龍掉落。",
> 
> "cropTier.mysticalagradditions.6": "6",
> 
> "crop.mysticalagradditions.nether_star": "Nether Star",
> "crop.mysticalagradditions.dragon_egg": "Dragon Egg"
> }

**Comment by BlakeBr0** [comment]
https://github.com/BlakeBr0/MysticalAgradditions/commit/fce25e68edcc260204c0b1c82da32712307abb7d
