### ISSUE TITLE
Supremium Paxel unable to break certain blocks

### ISSUE THREAD

**Issue by Hakura77** [BlakeBr0/MysticalAgradditions#55]
Using a supremium paxel I'm unable to break (thus far, this list is not exhaustive)
Glowstone, Glass Panes, silverfish eggs

Cannot gain any mining progression on those blocks at all, similar to attempting to mine bedrock.

**Comment by BlakeBr0** [comment]
I am unable to reproduce this issue in dev. Perhaps there's another mod causing this?

**Comment by BlakeBr0** [comment]
I will assume this issue is resolved due to inactivity.
