### ISSUE TITLE
I can’t use any of the mod’s tools to get monster seeds....

### ISSUE THREAD

**Issue by Suntz246** [BlakeBr0/MysticalAgradditions#56]
**I am a player from China, because English is not very good, so I use Google Translate to communicate with you. Maybe machine translation is not willing to accurately express my meaning. Please understand!**

mcVersion:1.12.2
moodVersion: the latest version

**I think the module has done a great job, but I recently encountered some unsolvable problems:
I can't use the tools in the module to get any seeds of the physical objects that can be obtained in the module.I have tried every tool of the module.Is it possible?Is it a problem with the configuration file?**

I cannot search for the correct answer to this question in China, I hope the author can reply to help! Thank you!

**Comment by BlakeBr0** [comment]
Soulium tinkers' construct tools and the Soulium Dagger from the base mod are the only ways to get mob chunks in the 1.12 version.
