### ISSUE TITLE
Crafting dosnt work with refined storage

### ISSUE THREAD

**Issue by bash90** [BlakeBr0/MysticalAgradditions#57]
![sceen](https://user-images.githubusercontent.com/12442142/87864978-530af000-c96f-11ea-8aad-9d343d46d0e5.png)
 as u can see it dosnt show the result of rsecipe

**Comment by BlakeBr0** [comment]
You're sure that's the recipe? Does it work elsewhere? Does it happen in a different modpack?

**Comment by bash90** [comment]
it works in crafting tables but just not in crafting grid from refined storage

**Comment by BlakeBr0** [comment]
I'm going to close this due to it being for a now unsupported version. If you run into this issue in modern versions feel free to reopen.
