### ISSUE TITLE
Nether star crop not growing

### ISSUE THREAD

**Issue by zackeezy** [BlakeBr0/MysticalAgradditions#6]
I planted a nether star seed and it keeps just flickering every so often but never grows.  I've left it going for a couple days and it has done nothing.

**Comment by BlakeBr0** [comment]
Tier 6 crops!
Current crops: Nether Star, Awakened Draconium
These crops have a 0% chance of dropping a second seed.
These crops can not be fertilized using Fertilized Essence or Mystical Fertilizer. (configurable)
These crops require a special block be placed underneath them to grow.
Press 'R' when hovering over a tier 6 essence to see the requirements in JEI.
(They can also be disabled in the config if you find them too overpowered)
