### ISSUE TITLE
Datapack support for Seeds

### ISSUE THREAD

**Issue by Warbringer12** [BlakeBr0/MysticalAgradditions#65]
I would like to add datapack support for the tier 6 seeds so I can customize the seed recipes

**Comment by BlakeBr0** [comment]
I'm assuming this is referring to the change I made in the base mod where all of the recipes are part of the mod datapack. If that's the case then I do plan on doing that pretty soon.

**Comment by Warbringer12** [comment]
yes is it referring to the change to the base mod you did where all the recipes are part of the mod datapack. so thanks for doing this :)
