### ISSUE TITLE
Mystical Agradditions Paxels don't seem "enchantable"

### ISSUE THREAD

**Issue by zaqhack** [BlakeBr0/MysticalAgradditions#66]
If you put one of the Inferium-line Paxels into an Enchanting Table (or with an enchanted book on an Anvil), no enchantments can be applied.

![Paxelchanting](https://user-images.githubusercontent.com/7399983/116651165-3e0bb600-a91e-11eb-8012-ee8ce7e24f4d.png)

I don't claim to know a lot about this, but in what troubleshooting I've been able to do, it seems like an issue between the tools and enchantment registries.

**Versions (please complete the following information):**
Part of FTB Endeavour 1.3.0 modpack
 - Minecraft: 1.16.5
 - Forge: 36.1.4
 - Cucumber: 1.16.4-4.1.9
 - Mystical Agriculture: 1.16.4-4.1.7
 - Mystical Agradditions: 1.16.4-4.1.5

**Comment by zaqhack** [comment]
P.S. I did also test this with regular Paxels from Mekanism, and in this modpack, they seem to work fine: 
![diamond-paxel](https://user-images.githubusercontent.com/7399983/116651758-92fbfc00-a91f-11eb-8de6-7054421aea55.png)

**Comment by AlgorithmLX** [comment]
So it is done that no Paxels, no Tools from Mystical Agriculture/Mystical Agradditions, can be enchanted
