### ISSUE TITLE
Re-implement TInkers' Construct integration

### ISSUE THREAD

**Issue by Bl4ckb33** [BlakeBr0/MysticalAgradditions#67]
I can't use any of the essences, or whatever variate they want, to manufacture parts of the tinker they won't even go in the forge
![Captura de tela 2021-05-18 002811](https://user-images.githubusercontent.com/84363973/118585936-3a768c80-b770-11eb-9581-39a6e1f37006.png)

**Versions (please complete the following information):**
 - Minecraft: 1.16.5
 - Forge: 36.1.0
 - Cucumber: 1.16.4-4.1.9
 - Mystical Agriculture: 1.16.4-4.1.7
 - Mystical Agradditions: 1.16.4-4.1.5

**Comment by BlakeBr0** [comment]
The integration was removed and will need to be re-added.

**Comment by BlakeBr0** [comment]
This is added in version 4.2.0.
