### ISSUE TITLE
Nether Star Seed duplicates when placed without soil by Cyclic Harvester.

### ISSUE THREAD

**Issue by Boomflex** [BlakeBr0/MysticalAgradditions#7]
Cyclic: v1.5.5
Mystical Agradditions: v1.0.2
Mystical Agriculture: v1.5.6

If you place a Nether Star seed without a crux next to a Cyclic Harvester, the Harvester will harvest the plant before it grows, replant one and dupe one in to its inventory.

I double checked the 2nd seed drop % and it is 0.

**Comment by BlakeBr0** [comment]
Does it happen with any other harvester?

**Comment by Boomflex** [comment]
I can't currently confirm. 

I do not believe so as I was using the Farmer from Actually Additions before changing to this and never noticed it then.

**Comment by BlakeBr0** [comment]
Maybe it's an issue with the harvester, unless theres some other way to make this happen.

**Comment by Shadow907G** [comment]
In 1.10.2 the baubles stuff harvest ring guarontees a seed with nether star seed and awakened draconium

**Comment by ouroborus** [comment]
We've been discussing this over in the Cyclic mod issues. It seems that the way Mystical Agradditions implements the block check prevents other mods from reliably detecting if the plant has grown completely.

Moving the block check from [`canGrow`](https://github.com/BlakeBr0/MysticalAgradditions/blob/master/1.12/src/main/java/com/blakebr0/mysticalagradditions/blocks/BlockTier6Crop.java#L65) to [`updateTick`](https://github.com/BlakeBr0/MysticalAgradditions/blob/master/1.12/src/main/java/com/blakebr0/mysticalagradditions/blocks/BlockTier6Crop.java#L32) would fix this.

**Comment by BlakeBr0** [comment]
Tell me something I dont know

**Comment by ouroborus** [comment]
Err...

> Maybe it's an issue with the harvester, unless theres some other way to make this happen.

This implies you didn't know how to fix it.

> Tell me something I dont know

This implies you do know how to fix it.

It seems to me that, between all the mods affected, this is the one that needs adjustment.

What's the root issue that's preventing this from getting fixed?

**Comment by BlakeBr0** [comment]
When I originally said it wasnt me I didnt know, then I realized the issue later. Never really got around to fixing it until now
