### ISSUE TITLE
Casting recipes for molton ingots from mystical agriculture not working

### ISSUE THREAD

**Issue by benbenlaw** [BlakeBr0/MysticalAgradditions#70]
**Describe the bug**
Casting recipes missing for all molten mystical ingots missing

**To Reproduce**
melt down a mystical ingot such as inferium
try to cast tool parts from it
nothing happens

**Expected behavior**
tool part to be created

**Screenshots / Scripts / Logs**
Please add your logs and scripts (if applicable).

**Versions (please complete the following information):**
 - Minecraft:1.16.5
 - Forge: 36.1.16
 - Cucumber: 2.1.10
 - Mystical Agriculture: 4.2.1
 - Mystical Agradditions: 4.2.0

**Comment by BlakeBr0** [comment]
Based on the issue in your repo I'm going to assume this is resolved. Were you using an older tinker's version?

**Comment by benbenlaw** [comment]
yeah this is now fixed with latest tinkers update
