### ISSUE TITLE
[1.18.1] Encountered an error during common_setup (tinkers construct)

### ISSUE THREAD

**Issue by Baggytrousers27** [BlakeBr0/MysticalAgradditions#81]
Error during startup

Error with listed mods (Below*):
Mystical Agradditions (mysticaladgradditions) encountered an error during the common_setup event phase

Error with Full Modpack:
Mystical Agradditions (mysticaladgradditions) encountered an error during the common_setup event phase
java.lang.NoSuchMethodError: Slimeknights.tconstruct.library.modifiers.Modficier: Method 'void <init>()' not found

[Crashlog](https://pastebin.com/tJHxmGrg)

*
 - Minecraft: 1.18.1
 - Forge: 39.0.75
 - Cucumber: 1.18.1-5.0.3
 - Mystical Agriculture: 1.18.1-5.0.3
 - Mystical Agradditions: 1.18.1-5.0.3
 - Mantle-1.18.1-1.8.31
 - TConstruct-1.18.1-3.4.0.34

**Comment by TheEssketitMan** [comment]
Can confirm I'm having this exact same problem, except:

- Forge: 39.0.76
and the crash report incase it helps
[crash-2022-02-13_13.05.49-fml.txt](https://github.com/BlakeBr0/MysticalAgradditions/files/8055493/crash-2022-02-13_13.05.49-fml.txt)

Tested it out with 
Mystical Aggriculture and Mystical Aggradditions 5.0.2 and it worked perfectly

**Comment by InfernumYT** [comment]
same for me

**Comment by BlakeBr0** [comment]
I guess the version of tinkers' I used isn't on curseforge yet. I archived the file for now and I'll restore it once that's out.

**Comment by BlakeBr0** [comment]
Restored the file as the new tinkers' build is out.
