### ISSUE TITLE
Insanium Furnace

### ISSUE THREAD

**Issue by duckhunter392** [BlakeBr0/MysticalAgradditions#82]
**Describe the bug**
Destroying the Insanium Furnace with any pickaxe will destroy the furnace, but does not drop it on the ground to be picked up and placed again

**To Reproduce**
- Spend countless hours upon hours obtaining inferium essence in survival mode
- Use said inferium (224 stacks to be exact) to create insanium
- Use the insanium to make a furnace
- Place said furnace down
- Use it once, be very happy with yourself, then decide to move it somewhere else
- Use diamond pickaxe on it
- Furnace goes poof, but it does not drop a furnace to pickup
- Pause for dramatic effect
- Cry
- Alt + F4
- Create a bug report on GitHub

**Expected behavior**
When you destroy an Insanium Furnace with a diamond pickaxe (or other high level modded pickaxe), it should drop an Insanium Furance for you to pick up.

**Screenshots / Scripts / Logs**
Not applicable.

**Versions (please complete the following information):**
 - Minecraft: 1.15.2
 - Forge: 31.2.47
 - Cucumber: 3.0.9
 - Mystical Agriculture: 3.0.10
 - Mystical Agradditions: 3.0.1

**Comment by BlakeBr0** [comment]
This mod doesn't add an insanium furnace
