### ISSUE TITLE
i want to add the block(anyblock) can grow tier1-6 in botany pot how? or not have this feature 

### ISSUE THREAD

**Issue by zen-zen-zen** [BlakeBr0/MysticalAgradditions#84]
**IMPORTANT: Feature requests will only be added to the latest supported Minecraft version.**

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by BlakeBr0** [comment]
You'll have to ask the botany pot devs.
