### ISSUE TITLE
Add a .cfg for Dragon_egg_seeds

### ISSUE THREAD

**Issue by Rosted420** [BlakeBr0/MysticalAgradditions#85]
**IMPORTANT: Feature requests will only be added to the latest supported Minecraft version.**
Is it possible to get this for 1.12.2 or shown a way to set up.

**Is your feature request related to a problem? Please describe.**
Can you add a Dragon egg seed .cfg file as there is none and I have to grow it through farm land without crop sticks.
**Describe the solution you'd like**
Add a .cfg file for dragon egg seeds 
**Describe alternatives you've considered**

**Additional context**

**Comment by BlakeBr0** [comment]
Sounds like you are asking for agricraft integration, which is not done by me. I'm not really sure how to set it up sorry.
