### ISSUE TITLE
Creative Tab bug

### ISSUE THREAD

**Issue by PrinceApache** [BlakeBr0/MysticalAgradditions#9]
All items are omnipresent in every creative tab, even the vanilla once.

**Comment by BlakeBr0** [comment]
Yeah I forgot about that when porting. It'll be fixed in the next update.

**Comment by PrinceApache** [comment]
Sounds awesome!

**Comment by YOYOK9** [comment]
Just to add on to this there is also an item locked in the item deletion box in the creative inventory.
